CREATE TABLE IF NOT EXISTS expenses(
    --EXPENSE_ID  INTEGER NOT NULL AUTO_INCREMENT,
    expense_id  INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    expense_uuid VARCHAR(36) NOT NULL,
    user_uuid VARCHAR(36) NOT NULL,
    expense_description VARCHAR(100) NOT NULL,
    expense_creation_date_time BIGINT NOT NULL,
    expense_category VARCHAR(30) NOT NULL,
    -- EXPENSE_AMOUNT DOUBLE NOT NULL,
    expense_amount DOUBLE PRECISION NOT NULL,
    expense_currency  VARCHAR(10) NOT NULL,
    PRIMARY KEY (expense_id)
);

CREATE TABLE IF NOT EXISTS expense_outbox_events (
  -- STORED_EVENT_ID INTEGER NOT NULL AUTO_INCREMENT,
  stored_event_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  event_id VARCHAR(36) NOT NULL,
  event_aggregate_id VARCHAR(128) NOT NULL,
  event_timestamp BIGINT NOT NULL,
  event_type VARCHAR(255) NOT NULL,
  event_payload TEXT NOT NULL,
  PRIMARY KEY (stored_event_id)
);

-- TODO Create index