CREATE TABLE IF NOT EXISTS USERS(
    USER_ID  INTEGER NOT NULL AUTO_INCREMENT,
    USER_UUID VARCHAR(36) NOT NULL,
    USER_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    ENCRYPTED_PASSWORD VARCHAR(128) NOT NULL,
    PRIMARY KEY (USER_ID)
);

-- TODO Create index