apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  selector:
    matchLabels:
      app: expense-tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: expense-tracker
          image: sy/expense-tracker:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080